### ISSUE TITLE
Nothing with this repo! SM64SF

### ISSUE THREAD

**Issue by Ruuka6009** [x4fx77x4f/sfc3#1]
Hey! the SM64SF looks really interesting but sadly you stopped it two years ago.. 
Why is that? if you want to talk, my discord is: cps.

Would love to know more! 
Bybyeee

**Comment by x4fx77x4f** [comment]
The version in that repository I stopped working on due to a bug in one of the VMs I was unable to discover the root cause of and thus unable to fix.
Later, I actually rewrote the entire project (sm64sf2) and got it to a stage where it was actually capable of displaying the intro. Initially, I didn't share that version of the repository because I felt I shouldn't share something that wasn't in a presentable state.
I archived it because I was tidying up my account and had long since lost interest in Garry's Mod. I came very close to deleting the repository as I was (and still am!) ashamed that my most starred repository is one that is not only unfinished but not even in a presentable state. I ultimately chose not to delete it as the archivist in me was opposed to the destruction of information (even if low value). I really wish GitHub had the option to unlist repositories (keep them publicly available but hard to find).
At the time I archived it, I didn't bother to push my rewrite before archiving as I had a faint memory of having tried to find it and being unable to. I really should have though as I was able to find it just now with ease by simply searching "sm64" in the directory I have dedicated to backups of my Garry's Mod install. I also found that I had some unpushed commits and uncommitted changes from the first version too. I went ahead and unarchived the repository and pushed both (the rewrite is on the "sm64sf2" branch).
